---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r }
activity <- read.table('activity.csv', na.strings='NA', sep=',', header=T, 
                       colClasses=c("numeric","Date","factor") )

```

## What is mean total number of steps taken per day?

```{r}

stepsPerDay <- tapply(activity$steps,activity$date, sum)

# histogram of the total number of steps taken each day
hist(stepsPerDay, col='red')


# mean steps per day 
meanPerDay <- mean(stepsPerDay,na.rm=T)
meanPerDay

# median steps per day
medianPreDay <- median(stepsPerDay,na.rm=T)
medianPreDay

```
## What is the average daily activity pattern?
```{r}
meanStepsPerInterval <- tapply(activity$steps,activity$interval, mean, na.rm=T)
```

## Imputing missing values
```{r}
# number of rows with missing values
missing <- length(activity$date) - sum(complete.cases(activity))
missing 

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity$day <- "weekday"
activity$day[weekdays(activity$date) %in% c("Saturday","Sunday")] <- "weekend"
acivityByDay <-split(activity,activity$day)
```
